AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  PackageName:
    Type: String

Resources:

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - "aws-elasticbeanstalk-ec2-role"

  TwelveFactorApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: 12factor-backing-service
      Description: Demo application for backing services factor

  ApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref TwelveFactorApplication
      Description: "Latest application version"
      SourceBundle:
        S3Bucket: twelve-factor-app-service-staging
        S3Key: !Ref PackageName

  TwelveFactorEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref TwelveFactorApplication
      Description: Development environment
      EnvironmentName: 12factor-backing-service
      OptionSettings:
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: IamInstanceProfile
          Value: !Ref InstanceProfile
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: InstanceType
          Value: "t3.micro"
        - Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: "SERVER_PORT"
          Value: "5000"
      SolutionStackName: "64bit Amazon Linux 2 v3.1.4 running Corretto 8"
      VersionLabel: !Ref ApplicationVersion
