#!/usr/bin/env bash

stack_name="twelve-factor-backing-service-stack"
package_name=$1

echo "Building $stack_name..."
aws cloudformation deploy \
  --capabilities CAPABILITY_IAM \
  --stack-name $stack_name \
  --template-file backing-service-app.yml \
  --parameter-overrides \
      PackageName="$package_name" \
      VersionDescription="1.2.3"
